# Generated by Django 5.0.6 on 2024-07-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('awaiting', 'awaiting'), ('busy', 'busy')], default='active', max_length=10)),
                ('experience', models.CharField(choices=[('senior', 'senior'), ('middle', 'middle'), ('junior', 'junior')], default='middle', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('pr_phone', models.CharField(max_length=13)),
                ('telegram', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.course')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.teacher')),
            ],
        ),
    ]
