# Generated by Django 5.0.6 on 2024-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram',
            field=models.CharField(max_length=25),
        ),
    ]
